### ISSUE TITLE
alife、next套件运行命令出错

### ISSUE THREAD

**Issue by Suixinlei** [fieteam/fie#11]
![](http://wx3.sinaimg.cn/mw1024/af9af7e7gy1fcoveznng1j20wz0h4n1d.jpg)
出现情况:
1. next套件中使用: fie theme install 后 fie start 出错
2. alife套件中使用 fie publish 出错
目前存在的解决方法：
用户删除项目中的node_modules并重新安装不会出现该错误

**Comment by hugohua** [comment]
这个是tnpm没装好，报错了。 重新安装下tnpm
