### ISSUE TITLE
fie publish 命令外网是否可用？

### ISSUE THREAD

**Issue by thomasyxy** [fieteam/fie#35]
请问外网能否使用 fie publish 发布到cdn，如果可以需要怎么配置？

➔ fie publish
[fie-toolkit-blue] 不建议在master分支上进行开发及发布,建议切换到 daily/x.y.z 分支进行开发
[fie-toolkit-blue] 开始提交到daily环境,大概需要几秒的时间,请稍等...
(node:15800) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: git is not a function
(node:15800) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

node v7.8.0   fie v2.7.2

**Comment by hugohua** [comment]
外网无法发布到CDN环境的。 因为 CDN发布 依赖的是内网 gitlab系统，而在外网无法访问gitlab，所以无法发布。

需要登录内网环境才能使用。
