### ISSUE TITLE
将工程拷贝至其他目录有， 使用Fie start无法启动

### ISSUE THREAD

**Issue by zunyan** [fieteam/fie#45]
将工程拷贝至其他目录有， 使用Fie start无法启动，报

> <span style="color: red"> [fie-config] 读取配置文件失败，请确认 fie.config.js 文件是否有语法错误</span>

 这是什么问题

**Comment by hugohua** [comment]
就是字面上的意思，确认一下 fie.config.js 是不是一个没有语法错误的 js 文件
