### ISSUE TITLE
安装qinniu套件时报错

### ISSUE THREAD

**Issue by ft19950915** [fieteam/fie#79]
? 请选择一个适合您项目的套件进行初始化: qnui -  基于QNUI的React+Redux+Next多页面应用解决方案

npminstall version: 2.30.1
npminstall args: E:\学习软件\Node\node.exe C:\Users\fengtao\.fie\node_modules\_npminstall@2.30.1@npminstall\bin\install.js --registry=http://registry.npm.taobao.org/ --china --stdio=inherit --cwd=E:\vs2012代码\fie-kdb-qinniu
'tnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
[core-error] 运行报错, 请在这里反馈问题给 hugohua https://github.com/fieteam/fie/issues/new
Error: install  error
    at ChildProcess.spawn.on.on (C:\Users\fengtao\.fie\node_modules\_fie-npm@1.3.5@fie-npm\lib\index.js:53:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\fengtao\.fie\node_modules\_cross-spawn@5.1.0@cross-spawn\lib\enoent.js:40:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by yubhbh** [comment]
你好.提供一下报错环境和截个图。
以下你可以试一下：
1. 建议用git bash 命令行工具，用管理员身份打开
2. 请确保你的node版本是6 + 
3. 删除 掉node_modules 重试。

**Comment by ft19950915** [comment]
是这样操作的node是6.14   删除了重试  但是还是显示缺少文件

**Comment by ft19950915** [comment]
是这样操作的node是6.14   删除了重试  但是还是显示缺少文件

**Comment by ft19950915** [comment]
是这样操作的node是6.14   删除了重试  但是还是显示缺少文件

**Comment by ft19950915** [comment]
是这样操作的node是6.14   删除了重试  但是还是显示缺少文件

**Comment by ft19950915** [comment]
是这样操作的node是6.14   删除了重试  但是还是显示缺少文件

**Comment by ft19950915** [comment]
是这样操作的node是6.14   删除了重试  但是还是显示缺少文件

**Comment by ft19950915** [comment]
是这样操作的node是6.14   删除了重试  但是还是显示缺少文件
