### ISSUE TITLE
没人处理消息吗？

### ISSUE THREAD

**Issue by ft19950915** [fieteam/fie#81]
旺旺也加不上

**Comment by yubhbh** [comment]
你好.提供一下报错环境和截个图。
以下你可以试一下：
1. 建议用git bash 命令行工具，用管理员身份打开
2. 请确保你的node版本是6 + 
3. 删除 掉node_modules 重试。

**Comment by ft19950915** [comment]
是用的git bash   node是6.14   删掉node_modules文件夹是删除项目中的文件还是  .fie里面的

**Comment by ft19950915** [comment]
可以加一下旺旺群吗
